spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://sathvikdatabase.cs1e2o4ayrnf.us-east-1.rds.amazonaws.com/sathvikbackend}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sathvik}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Sathvik2086}

spring.jpa.hibernate.ddl-auto=update

# Gmail SMTP Authentication Configuration (MFA)
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:sathvik2086@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:dtmmlrxajadmrool}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.jpa.show-sql=true

server.port=8080

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
